import Head from 'next/head';

export default function Home() {
  return (
    <div className="main">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="mt-5 text-center text-3xl font-medium italic underline text-blue-500 animate-pulse">
        Hello world!
      </h1>
    </div>
  );
}
